import type { Section } from "./types";
import { DEFAULT_REPO, DTYPES, HNX_DEVICES, KNOWN_MODELS, action, area, combo, is, list, num, path, pick, samplingFields, secret, text, toggle } from "./shared";

const modelSource = [
  combo("repoId", "--repo-id", "Model", KNOWN_MODELS, { placeholder: DEFAULT_REPO, showIf: (v) => !v.modelDir }),
  path("modelDir", "--model-dir", "Local snapshot or .gguf", "dir"),
];
const runtime = [
  text("device", "--device", "Device", { placeholder: "auto", advanced: true }),
  pick("dtype", "--dtype", "Precision", ["", ...DTYPES], { advanced: true }),
];
const subBit = [
  pick("hnxDevice", "--hnx-device", "Sub-bit device", ["", ...HNX_DEVICES], { advanced: true }),
  text("cacheBytes", "--cache-bytes", "Sub-bit decode cache", { advanced: true, placeholder: "512M, 2G" }),
];

export const inferenceSection: Section = {
  id: "inference",
  title: "Chat & inference",
  icon: "chat",
  blurb: "Talk to any HyperNix-family model, sample text, complete code, and run the agent TUIs — right here in the app.",
  groups: [
    {
      title: "Run a model",
      commands: [
        {
          id: "chat",
          title: "Chat",
          summary: "Interactive chat with any supported model. Type into the console; leave Message empty for a REPL.",
          icon: "chat",
          program: "hypernix",
          base: ["chat"],
          keywords: "repl talk llm",
          fields: [
            ...modelSource,
            text("system", "--system", "System prompt", { wide: true }),
            area("message", "--message", "Message (one turn)", { placeholder: "Leave empty for an interactive chat" }),
            ...samplingFields({ maxNew: "256", temperature: "0.7", topK: "40" }),
            ...runtime,
            ...subBit,
            text("revision", "--revision", "Revision", { advanced: true }),
            secret("token", "--token", "HF token", { advanced: true, placeholder: "from Settings" }),
            toggle("quiet", "--quiet", "Quiet", { advanced: true }),
          ],
        },
        {
          id: "generate",
          title: "Generate",
          summary: "Sample text from a local snapshot or GGUF.",
          icon: "sparkles",
          program: "hypernix",
          base: ["generate"],
          fields: [
            path("modelDir", "--model-dir", "Snapshot or .gguf", "dir", { required: true }),
            area("prompt", "--prompt", "Prompt", { placeholder: "Empty starts from BOS" }),
            ...samplingFields({ maxNew: "64", temperature: "1.0", topK: "50" }),
            ...runtime,
            ...subBit,
          ],
        },
        {
          id: "oven",
          title: "Oven · code",
          summary: "Code completion and fill-in-the-middle.",
          icon: "cooker",
          program: "hypernix",
          base: ["oven"],
          keywords: "code completion fim",
          fields: [
            ...modelSource,
            pick("mode", undefined, "Mode", [
              { value: "complete", label: "Complete a prompt" },
              { value: "fim", label: "Fill in the middle" },
            ], { default: "complete" }),
            area("prompt", "--prompt", "Prompt", { showIf: is("mode", "complete") }),
            area("prefix", "--fill-prefix", "Prefix", { showIf: is("mode", "fim"), required: true }),
            area("suffix", "--fill-suffix", "Suffix", { showIf: is("mode", "fim"), required: true }),
            ...samplingFields({ maxNew: "256", temperature: "0.2", topK: "40" }),
            ...runtime,
            path("savePt", "--save-pt", "Also save torch bundle", "save", { advanced: true }),
            toggle("auto", "--auto", "Unattended", { advanced: true }),
          ],
        },
        {
          id: "multilama",
          title: "multilama",
          summary: "One interface over vanilla llama.cpp, ik_llama.cpp, PrismML and KoboldCpp.",
          icon: "layers",
          program: "multilama",
          base: [],
          fields: [
            action(["list", "chat"]),
            list("args", undefined, "Arguments", "space", { positional: true, wide: true, showIf: is("action", "chat"), placeholder: "model.gguf" }),
          ],
        },
        {
          id: "websearch",
          title: "Web search",
          summary: "The search backend behind chat and the assistant.",
          icon: "search",
          program: "hypernix",
          base: ["websearch"],
          fields: [
            text("query", undefined, "Query", { positional: true, required: true, wide: true }),
            num("max", "-n", "Max results"),
            pick("engine", "-e", "Engine", ["", "auto", "duckduckgo", "bing"]),
            toggle("json", "--json", "JSON", { advanced: true }),
          ],
        },
      ],
    },
    {
      title: "Agents & TUIs",
      commands: [
        {
          id: "hyped-pro",
          title: "hyped-pro",
          summary: "The OpenTUI terminal client: ctrl+p picks a model, /noodle runs the executor, /t1 routes through a server.",
          icon: "terminal",
          program: "hyped-pro",
          base: [],
          tui: true,
          fields: [],
        },
        {
          id: "hyped",
          title: "hyped",
          summary: "The simple one: a local model, a prompt, and dots for everything else.",
          icon: "terminal",
          program: "hyped",
          base: [],
          tui: true,
          fields: [],
        },
        {
          id: "hyped-plus",
          title: "hyped-plus",
          summary: "The previous hyped-pro, a readline TUI with /gui, /t1api and /noodle.",
          icon: "terminal",
          program: "hyped-plus",
          base: [],
          tui: true,
          fields: [],
        },
        {
          id: "hyped-pro-gui",
          title: "hyped-pro desktop",
          summary: "hyped-pro's own Qt6/GTK4 desktop window.",
          icon: "monitor",
          program: "hyped-pro-gui",
          base: [],
          fields: [],
        },
        {
          id: "noodle",
          title: "noodle",
          summary: "Run AI agents against a task in a sandboxed workspace.",
          icon: "bot",
          program: "noodle",
          base: [],
          keywords: "agent autonomous executor",
          fields: [
            area("task", undefined, "Task", { positional: true, placeholder: "write fizzbuzz.py" }),
            list("models", "-m", "Models", "repeat", { placeholder: "ollama:llama3.2", wide: true }),
            path("tasksFile", "-f", "Tasks file", "file"),
            path("workspace", "-w", "Workspace", "dir", { placeholder: "./noodle-work" }),
            num("parallel", "--parallel", "Parallel"),
            num("maxTurns", "--max-turns", "Max turns", { advanced: true }),
            toggle("execute", "--execute", "Let agents run code", { help: "Only in a disposable workspace." }),
            toggle("memory", "--memory", "Durable memory", { advanced: true }),
            text("verify", "--verify", "Verify with", { placeholder: "pytest -q", advanced: true }),
            toggle("noSyntax", "--no-syntax-check", "No syntax check", { advanced: true }),
            toggle("providers", "--providers", "List providers and stop"),
            toggle("quiet", "--quiet", "Summary only", { advanced: true }),
          ],
        },
        {
          id: "assistant",
          title: "Voice assistant",
          summary: "Local assistant with voice commands (ASR + LLM + TTS).",
          icon: "bot",
          program: "hypernix",
          base: ["assistant"],
          tui: true,
          fields: [],
        },
        {
          id: "vera",
          title: "Vera",
          summary: "The Vera assistant CLI.",
          icon: "bot",
          program: "hypernix",
          base: ["vera"],
          tui: true,
          fields: [],
        },
      ],
    },
  ],
};
