import type { Section } from "./types";
import {
  ARCHES, ALL_TIERS, DEFAULT_REPO, KNOWN_MODELS, QUANT_ALIASES, action, combo, is, list, num, path, pick, secret, text, toggle, tri,
} from "./shared";

export const modelsSection: Section = {
  id: "models",
  title: "Models & GGUF",
  icon: "boxes",
  blurb: "Download snapshots from Hugging Face, convert them to GGUF, quantise, verify and publish.",
  groups: [
    {
      title: "Pipeline",
      commands: [
        {
          id: "all",
          title: "Full pipeline",
          summary: "Download → convert → quantise in one run, optionally uploading the result.",
          icon: "workflow",
          program: "hypernix",
          base: ["all"],
          doc: "wiki/Quantization.md",
          keywords: "download convert quantize gguf upload all",
          fields: [
            combo("repoId", "--repo-id", "Model", KNOWN_MODELS, { placeholder: DEFAULT_REPO, help: "Short name or full Hugging Face repo id." }),
            path("outputDir", "--output-dir", "Output folder", "dir", { placeholder: "./hypernix-gguf" }),
            list("quants", "--quants", "Quantisations", "space", {
              options: QUANT_ALIASES.map((value) => ({ value })),
              default: ["fp32", "fp16"],
              wide: true,
              help: "One fp16 intermediate is made and reused for every k-quant.",
            }),
            path("modelDir", "--model-dir", "Existing snapshot", "dir", { help: "Reuse a local snapshot instead of downloading." }),
            toggle("auto", "--auto", "Unattended", { help: "Walk back through llama.cpp releases, fall back to llama-cpp-python." }),
            text("revision", "--revision", "Revision", { advanced: true }),
            text("modelDirName", "--model-dir-name", "Cache folder name", { advanced: true }),
            text("name", "--name", "Model name", { advanced: true, placeholder: "HyperNix" }),
            combo("arch", "--arch", "Architecture", ARCHES, { advanced: true, placeholder: "hypernix" }),
            num("nHead", "--n-head", "Attention heads", { advanced: true }),
            num("contextLength", "--context-length", "Context length", { advanced: true }),
            num("threads", "--threads", "Threads", { advanced: true }),
            path("llamaQuantize", "--llama-quantize", "llama-quantize binary", "file", { advanced: true }),
            toggle("noAutoFetch", "--no-auto-fetch", "Never download llama-quantize", { advanced: true }),
            toggle("keep", "--keep-intermediate", "Keep intermediate files", { advanced: true }),
            text("uploadTo", "--upload-to", "Upload to repo", { advanced: true, placeholder: "you/model-gguf" }),
            toggle("uploadPrivate", "--upload-private", "Private upload", { advanced: true }),
            secret("token", "--token", "HF token", { advanced: true, placeholder: "from Settings" }),
          ],
        },
        {
          id: "download",
          title: "Download",
          summary: "Fetch a Hugging Face snapshot to disk and sanity-check it.",
          icon: "download",
          program: "hypernix",
          base: ["download"],
          keywords: "huggingface hf snapshot fetch",
          fields: [
            combo("repoId", "--repo-id", "Model", KNOWN_MODELS, { placeholder: DEFAULT_REPO }),
            path("localDir", "--local-dir", "Save to", "dir"),
            text("revision", "--revision", "Revision", { advanced: true }),
            path("cacheDir", "--cache-dir", "Cache folder", "dir", { advanced: true }),
            toggle("noVerify", "--no-verify", "Skip verification", { advanced: true }),
            toggle("quiet", "--quiet", "Quiet", { advanced: true }),
            secret("token", "--token", "HF token", { advanced: true, placeholder: "from Settings" }),
          ],
        },
        {
          id: "convert",
          title: "Convert",
          summary: "Make an F32/F16 GGUF from a snapshot, .safetensors, Brewer model or .pt — or convert and quantise in one step.",
          icon: "shuffle",
          program: "hypernix",
          base: ["convert"],
          keywords: "gguf safetensors f16 pipeline",
          fields: [
            path("source", undefined, "Source", "dir", { positional: true, required: true, help: "Model folder, .safetensors, Brewer folder/.pt, or .gguf." }),
            path("output", "-o", "Output", "save", { extensions: ["gguf"] }),
            combo("quant", "-Q", "Quantise to", ALL_TIERS, { help: "Any llama.cpp type, HyperNix tier or hybrid. Implies -P." }),
            pick("dtype", "--dtype", "Float width", ["", "fp16", "fp32"], { placeholder: "fp16" }),
            toggle("pipeline", "-P", "Pipeline (-P)", { advanced: true }),
            toggle("keep", "--keep-intermediate", "Keep the F16 GGUF", { advanced: true }),
            path("imatrix", "--imatrix", "Importance matrix", "file", { advanced: true }),
            combo("arch", "--arch", "Architecture", ARCHES, { advanced: true, placeholder: "hypernix" }),
            text("name", "--name", "Model name", { advanced: true }),
            num("nHead", "--n-head", "Attention heads", { advanced: true }),
            num("contextLength", "--context-length", "Context length", { advanced: true }),
          ],
        },
        {
          id: "quantize",
          title: "Quantise (llama-quantize)",
          summary: "Run llama-quantize on an F16/F32 GGUF, or hyprslug with -hnx.",
          icon: "layers",
          program: "hypernix",
          base: ["quantize"],
          keywords: "k-quant q4_k_m llama.cpp",
          fields: [
            path("source", "--source", "Source GGUF", "file", { required: true, extensions: ["gguf"] }),
            path("output", "--output", "Output", "save", { required: true, extensions: ["gguf"] }),
            pick("type", "--type", "Type", QUANT_ALIASES, { required: true, default: "q4_k_m" }),
            toggle("hnx", "-hnx", "Use hyprslug (-hnx)", { help: "Never touch llama.cpp." }),
            toggle("auto", "--auto", "Unattended", { advanced: true }),
            num("threads", "--threads", "Threads", { advanced: true }),
            path("llamaQuantize", "--llama-quantize", "llama-quantize binary", "file", { advanced: true }),
            toggle("noAutoFetch", "--no-auto-fetch", "Never download llama-quantize", { advanced: true }),
            path("imatrix", "--imatrix", "Importance matrix (JSON)", "file", { advanced: true }),
            tri("emb", "--quantize-embeddings", "--no-quantize-embeddings", "Token embeddings", { advanced: true }),
            tri("head", "--quantize-output", "--no-quantize-output", "Output head", { advanced: true }),
          ],
        },
      ],
    },
    {
      title: "Inspect & publish",
      commands: [
        {
          id: "verify",
          title: "Verify GGUF",
          summary: "Read-check a GGUF and print its headers.",
          icon: "badge",
          program: "hypernix",
          base: ["verify"],
          fields: [
            path("gguf", undefined, "GGUF file", "file", { positional: true, required: true, extensions: ["gguf"] }),
            toggle("tensors", "--tensors", "List tensors"),
          ],
        },
        {
          id: "info",
          title: "Package info",
          summary: "HyperNix package details, plus a GGUF header summary.",
          icon: "info",
          program: "hypernix",
          base: ["info"],
          fields: [path("gguf", "--gguf", "GGUF file", "file", { extensions: ["gguf"] })],
        },
        {
          id: "upload",
          title: "Upload",
          summary: "Push files to a Hugging Face repo.",
          icon: "upload",
          program: "hypernix",
          base: ["upload"],
          keywords: "huggingface publish push",
          fields: [
            list("files", undefined, "Files", "space", { positional: true, required: true, pathMode: "file", wide: true }),
            text("repoId", "--repo-id", "Repo", { placeholder: "ray0rf1re/HyperNix.1-gguf" }),
            text("message", "--commit-message", "Commit message", { placeholder: "Add HyperNix GGUF quantizations" }),
            toggle("private", "--private", "Private repo"),
            secret("token", "--token", "HF token", { advanced: true, placeholder: "from Settings" }),
          ],
        },
        {
          id: "headers",
          title: "Sub-bit headers & server",
          summary: "Self-describing GGUF headers, the compat export, and the sub-bit OpenAI-compatible server for LM Studio.",
          icon: "tag",
          program: "hypernix",
          base: ["hyprslug-headers"],
          keywords: "lm studio stamp wrap serve hyprslug-headers",
          fields: [
            action(["status", "scan", "show", "serve", "stamp", "wrap", "install", "install-model", "uninstall"]),
            path("target", undefined, "Model / folder", "file", { positional: true, showIf: is("action", "show", "stamp", "wrap", "install-model", "serve", "scan") }),
            toggle("json", "--json", "JSON output", { advanced: true }),
          ],
        },
        {
          id: "runtime",
          title: "Runtime for other apps",
          summary: "Use HyperNix's llama.cpp from LM Studio, Jan, Open WebUI, Continue, Zed or Cursor.",
          icon: "plug",
          program: "hypernix",
          base: ["runtime"],
          keywords: "llama-server openai lm studio serve",
          fields: [
            action(["status", "path", "serve", "install", "restore"]),
            path("model", undefined, "Model", "file", { positional: true, required: true, extensions: ["gguf"], showIf: is("action", "serve") }),
            text("host", "--host", "Host", { showIf: is("action", "serve"), placeholder: "127.0.0.1" }),
            num("port", "--port", "Port", { showIf: is("action", "serve") }),
            num("ngl", "-ngl", "GPU layers", { showIf: is("action", "serve") }),
            num("ctx", "-c", "Context", { showIf: is("action", "serve") }),
            text("alias", "--alias", "Alias", { showIf: is("action", "serve"), advanced: true }),
            toggle("printOnly", "--print-only", "Print the command only", { showIf: is("action", "serve"), advanced: true }),
            path("target", "--target", "Runtime folder", "dir", { showIf: is("action", "install", "restore") }),
            toggle("yes", "--yes", "Confirm changes", { showIf: is("action", "install", "restore"), help: "Without it, nothing is applied." }),
            toggle("dryRun", "--dry-run", "Dry run", { showIf: is("action", "install"), advanced: true }),
            path("build", "--build", "llama.cpp build", "dir", { advanced: true }),
            toggle("json", "--json", "JSON output", { advanced: true }),
          ],
        },
        {
          id: "fetch-llama-quantize",
          title: "Fetch llama-quantize",
          summary: "Pre-seed the llama-quantize cache from llama.cpp releases.",
          icon: "download",
          program: "hypernix",
          base: ["fetch-llama-quantize"],
          fields: [
            toggle("force", "--force", "Re-download"),
            toggle("auto", "--auto", "Fall back to llama-cpp-python"),
            num("search", "--search-releases", "Releases to probe", { placeholder: "10", advanced: true }),
            toggle("quiet", "--quiet", "Quiet", { advanced: true }),
          ],
        },
        {
          id: "waiter-fetch",
          title: "Resolve a GGUF link",
          summary: "Turn a Hugging Face page or file link into a download plan.",
          icon: "globe",
          program: "waiter",
          base: ["fetch"],
          keywords: "huggingface gguf link waiter",
          fields: [
            text("link", undefined, "Link or owner/repo[:QUANT]", { positional: true, placeholder: "bartowski/Qwen3-8B-GGUF:Q5_K_M", wide: true }),
            pick("prefer", "--prefer", "Prefer", ["", "strict", "file", "page"]),
            toggle("local", "--local", "Resolve here, not on the server"),
            toggle("offline", "--offline", "From the links alone", { advanced: true }),
            toggle("noVision", "--no-vision", "Skip vision projector", { advanced: true }),
            text("page", "--page", "Model page URL", { advanced: true }),
            text("file", "--file", "Direct file URL", { advanced: true }),
          ],
        },
      ],
    },
  ],
};

