import type { Section } from "./types";
import { ALL_TIERS, STEAMROLLER_TIERS, action, combo, is, list, num, path, pick, text, toggle, tri } from "./shared";

const notTool = (v: Record<string, unknown>) => !v.listTiers;

export const quantSection: Section = {
  id: "quant",
  title: "Quantisation lab",
  icon: "layers3",
  blurb: "hyprslug, steamroller, multi-quant bundles, speculative-decoding drafts and importance matrices. No llama.cpp needed.",
  groups: [
    {
      title: "Quantisers",
      commands: [
        {
          id: "hyprslug",
          title: "hyprslug",
          summary: "Quantise a GGUF to any llama.cpp type or a HyperNix sub-bit tier — without a llama.cpp binary.",
          icon: "gem",
          program: "hyprslug",
          base: [],
          doc: "wiki/HyprSlug.md",
          keywords: "doomslug dstd sub-bit iq0.5 int3 fp8",
          fields: [
            path("source", undefined, "Source GGUF", "file", { positional: true, extensions: ["gguf"], showIf: notTool }),
            combo("tier", undefined, "Target tier", ALL_TIERS, { positional: true, placeholder: "Q4_K_M", showIf: (v) => notTool(v) && !v.multi && !v.check && !v.draft }),
            path("output", "-o", "Output", "save", { extensions: ["gguf"], showIf: notTool }),
            path("imatrix", "--imatrix", "Importance matrix (JSON)", "file", { showIf: notTool }),
            tri("emb", "--quantize-embeddings", "--no-quantize-embeddings", "Token embeddings", { help: "Sub-bit tiers leave them float by default." }),
            tri("head", "--quantize-output", "--no-quantize-output", "Output head"),
            toggle("listTiers", "--list-tiers", "List every tier and stop"),
            toggle("check", "--check", "Only check it loads in llama.cpp", { advanced: true }),
            path("repairTo", "--repair-to", "Repair to", "save", { advanced: true, help: "Widen tensors llama.cpp would refuse back to F32." }),
            text("multi", "--multi", "Bundle tiers", { advanced: true, placeholder: "Q4_K_M,Q6_K,IQ0.5_XXXL" }),
            text("default", "--default", "Default variant", { advanced: true, showIf: (v) => !!v.multi }),
            toggle("noShare", "--no-share", "Don't share identical tensors", { advanced: true, showIf: (v) => !!v.multi }),
            toggle("listVariants", "--list-variants", "List bundle variants", { advanced: true }),
            text("extract", "--extract", "Extract variant", { advanced: true }),
            pick("draft", "--draft", "Derive a draft", ["", "dflash1", "dflash2"], { advanced: true }),
            text("draftQuant", "--draft-quant", "Draft format", { advanced: true, placeholder: "Q4_0", showIf: (v) => !!v.draft }),
            num("draftDepth", "--draft-depth", "Draft depth", { advanced: true, placeholder: "0.25", step: 0.05, showIf: (v) => !!v.draft }),
            num("draftTokens", "--draft-tokens", "Draft tokens", { advanced: true, placeholder: "4", showIf: (v) => !!v.draft }),
            text("draftLayers", "--draft-layers", "Draft layers", { advanced: true, placeholder: "0,7,15", showIf: (v) => !!v.draft }),
            toggle("json", "--json", "JSON output", { advanced: true }),
            toggle("quiet", "-q", "Quiet", { advanced: true }),
          ],
        },
        {
          id: "steamroller",
          title: "steamroller",
          summary: "Roll a model down to a narrow tier, staging through Q3_K_L.",
          icon: "snail",
          program: "steamroller",
          base: [],
          keywords: "descend iq1_m q3_k_l",
          fields: [
            path("source", undefined, "Source GGUF", "file", { positional: true, extensions: ["gguf"], showIf: notTool }),
            pick("target", undefined, "Target tier", STEAMROLLER_TIERS, { positional: true, default: "IQ1_M", showIf: notTool }),
            path("output", "-o", "Output", "save", { extensions: ["gguf"], showIf: notTool }),
            path("imatrix", "--imatrix", "Importance matrix", "file", { help: "Strongly advised below 3 bits.", showIf: notTool }),
            toggle("hnx", "-hnx", "hyprslug only (-hnx)", { help: "Required for the IQ0.x tiers." }),
            toggle("plan", "--plan", "Show the plan and stop"),
            toggle("listTiers", "--list-tiers", "List tiers and stop"),
            pick("sourceFormat", "--source-format", "Source format", ["", "FP32", "BF16", "FP16", "FP8", "Q8_0"], { advanced: true }),
            text("parameters", "--parameters", "Parameter count", { advanced: true, placeholder: "7e9" }),
            toggle("noStaging", "--no-staging", "Skip Q3_K_L staging", { advanced: true }),
            toggle("keep", "--keep-intermediates", "Keep intermediates", { advanced: true }),
            toggle("json", "--json", "JSON output", { advanced: true }),
          ],
        },
        {
          id: "bundle",
          title: "Multi-quant bundle",
          summary: "Several quantisations in one GGUF; stock llama.cpp runs the default variant.",
          icon: "package",
          program: "hnx-bundle",
          base: [],
          keywords: "multiquant hnx-bundle",
          fields: [
            action(["build", "list", "extract", "strip"]),
            path("source", undefined, "Source GGUF", "file", { positional: true, required: true, extensions: ["gguf"] }),
            text("targets", undefined, "Tiers", { positional: true, required: true, placeholder: "Q4_K_M,Q6_K,Q8_0", showIf: is("action", "build") }),
            text("tier", undefined, "Variant", { positional: true, required: true, showIf: is("action", "extract") }),
            path("output", "-o", "Output", "save", { extensions: ["gguf"], showIf: is("action", "build", "extract", "strip") }),
            text("default", "--default", "Default variant", { showIf: is("action", "build") }),
            path("imatrix", "--imatrix", "Importance matrix", "file", { advanced: true, showIf: is("action", "build") }),
            toggle("noShare", "--no-share", "Store every variant separately", { advanced: true, showIf: is("action", "build") }),
            toggle("json", "--json", "JSON output", { advanced: true }),
          ],
        },
      ],
    },
    {
      title: "Drafts & calibration",
      commands: [
        {
          id: "dflash2",
          title: "dflash2 · embedded draft",
          summary: "Derive a draft model and carry it inside the base GGUF for speculative decoding.",
          icon: "rabbit",
          program: "dflash2",
          base: [],
          doc: "wiki/Dflash2.md",
          keywords: "speculative decoding draft",
          fields: [
            action(["attach", "info", "extract", "strip"]),
            path("source", undefined, "Base GGUF", "file", { positional: true, required: true, extensions: ["gguf"] }),
            path("output", "-o", "Output", "save", { required: true, extensions: ["gguf"], showIf: is("action", "attach", "extract", "strip") }),
            num("depth", "--depth", "Layers kept", { placeholder: "0.25", step: 0.05, showIf: is("action", "attach") }),
            text("layers", "--layers", "Exact layers", { placeholder: "0,7,15", showIf: is("action", "attach"), advanced: true }),
            text("quant", "--quant", "Draft format", { placeholder: "Q4_0", showIf: is("action", "attach") }),
            num("draftTokens", "--draft-tokens", "Draft tokens", { showIf: is("action", "attach"), advanced: true }),
            toggle("noShareEmb", "--no-share-embeddings", "Separate embeddings", { showIf: is("action", "attach"), advanced: true }),
            toggle("json", "--json", "JSON output", { advanced: true, showIf: is("action", "attach", "info") }),
          ],
        },
        {
          id: "dflash1",
          title: "dflash1 · standalone draft",
          summary: "A separate draft GGUF for llama.cpp's --model-draft.",
          icon: "rabbit",
          program: "dflash1",
          base: [],
          fields: [
            path("source", undefined, "Base GGUF", "file", { positional: true, required: true, extensions: ["gguf"] }),
            path("output", "-o", "Output", "save", { extensions: ["gguf"] }),
            list("extra", undefined, "More arguments", "space", { positional: true, advanced: true, placeholder: "see dflash1 --help" }),
          ],
        },
        {
          id: "imatrix",
          title: "Importance matrix",
          summary: "Measure an imatrix from calibration text, or convert between .imatrix and JSON.",
          icon: "microscope",
          program: "hnx-imatrix",
          base: [],
          keywords: "imatrix calibration",
          fields: [
            action(["measure", "convert", "show"]),
            text("model", undefined, "Model (folder or HF id)", { positional: true, required: true, showIf: is("action", "measure") }),
            path("source", undefined, "Source", "file", { positional: true, required: true, showIf: is("action", "convert", "show") }),
            list("text", "-t", "Calibration text", "repeat", { pathMode: "file", showIf: is("action", "measure"), help: "A file, folder, or literal text. Several allowed." }),
            path("output", "-o", "Output", "save", { required: true, showIf: is("action", "measure", "convert") }),
            num("chunkTokens", "--chunk-tokens", "Chunk tokens", { showIf: is("action", "measure"), advanced: true }),
            num("maxChunks", "--max-chunks", "Max chunks", { showIf: is("action", "measure"), advanced: true }),
            text("device", "--device", "Device", { placeholder: "cuda, mps", showIf: is("action", "measure"), advanced: true }),
            toggle("simple", "--simple", "Bare JSON mapping", { showIf: is("action", "measure", "convert"), advanced: true }),
            num("tensors", "-n", "Tensors to show", { showIf: is("action", "show") }),
          ],
        },
      ],
    },
  ],
};
