import type { Section } from "./types";
import { action, is, list, num, path, pick, text, toggle } from "./shared";

export const monitorSection: Section = {
  id: "monitor",
  title: "Monitor",
  icon: "activity",
  blurb: "The dashboards, running inside the app: tvtop-max, tvtop-pro, cctvtop, the steampunk map, and the hardware guards.",
  groups: [
    {
      title: "Dashboards",
      commands: [
        {
          id: "tvtop-max",
          title: "tvtop-max",
          summary: "The machine and the run on it: script modules, model architecture, Pressure Cooker, logs and warnings.",
          icon: "dashboard",
          program: "tvtop-max",
          base: [],
          tui: true,
          doc: "wiki/TvTopMax.md",
          keywords: "tvtopmax monitor training dashboard",
          fields: [
            pick("layout", undefined, "Layout", [
              { value: "", label: "Automatic" },
              { value: "-w", label: "Desktop" },
              { value: "-s", label: "Phone" },
            ], { positional: true }),
            path("log", "-l", "Training log", "file"),
            path("script", "-S", "Training script", "file"),
            num("pid", "-P", "Process id", { advanced: true }),
            num("refresh", "-r", "Refresh s", { placeholder: "1", advanced: true }),
            text("hide", "--hide", "Hide panels", { placeholder: "procs,modules", advanced: true }),
          ],
        },
        {
          id: "tvtoppro",
          title: "tvtop-pro",
          summary: "tvtop++'s stats, presented like btop++, with themes and stat modules.",
          icon: "chart",
          program: "tvtoppro",
          base: [],
          tui: true,
          fields: [
            path("log", "--log", "Training log", "file"),
            text("theme", "--theme", "Theme"),
            text("modules", "--modules", "Modules", { placeholder: "all" }),
            num("refresh", "--refresh", "Refresh s", { advanced: true }),
            text("stale", "--stale-after", "Stale after", { placeholder: "7d", advanced: true }),
            toggle("noProc", "--no-processes", "Hide processes", { advanced: true }),
            toggle("noIntro", "--no-intro", "Skip intro", { advanced: true }),
            toggle("once", "--once", "One frame and exit", { advanced: true }),
            toggle("listThemes", "--list-themes", "List themes", { advanced: true }),
            toggle("listModules", "--list-modules", "List modules", { advanced: true }),
            toggle("findRun", "--find-run", "Find the busiest run", { advanced: true }),
          ],
        },
        { id: "cctvtop", title: "cctvtop", summary: "The C++ training dashboard.", icon: "monitor", program: "cctvtop", base: [], tui: true, fields: [] },
        {
          id: "hnx-map",
          title: "Steampunk map",
          summary: "Your model as a schematic: dials for parameters, pipes for layers, steam for live data.",
          icon: "map",
          program: "hnx-map",
          base: [],
          tui: true,
          fields: [list("config", undefined, "Config (optional)", "space", { positional: true, placeholder: "config poly 64", advanced: true })],
        },
      ],
    },
    {
      title: "Hardware guards",
      commands: [
        {
          id: "eth",
          title: "Ethanol · GPU clocks",
          summary: "Show or offset GPU clocks. Applying needs Confirm; level 0 always resets.",
          icon: "zap",
          program: "eth",
          base: [],
          confirm: "Overclocking can crash your machine and may damage hardware. Continue?",
          fields: [
            pick("level", undefined, "Level", ["status", "auto", "reset", "0", "5", "10", "15", "20", "25", "30"], { positional: true, default: "status" }),
            toggle("confirm", "--confirm", "Confirm (apply)"),
            num("gpu", "--gpu", "GPU index", { advanced: true }),
          ],
        },
        {
          id: "ups",
          title: "UPS · outage watch",
          summary: "Weather and scheduled-outage threat status, so training can checkpoint in time.",
          icon: "alert",
          program: "ups",
          base: [],
          fields: [
            action(["status", "watch"]),
            num("lat", "--lat", "Latitude", { step: 0.01 }),
            num("lon", "--lon", "Longitude", { step: 0.01 }),
            num("interval", "--interval", "Interval s", { placeholder: "300", showIf: is("action", "watch") }),
            toggle("offline", "--offline", "Offline"),
            toggle("json", "--json", "JSON", { advanced: true }),
          ],
        },
        {
          id: "prot",
          title: "Protect",
          summary: "Hardware health and monitor protection.",
          icon: "shield",
          program: "hypernix",
          base: ["prot"],
          tui: true,
          fields: [
            pick("action", undefined, "Action", ["start", "bind"], { positional: true, default: "start" }),
            toggle("force", "--force", "Force", { showIf: is("action", "start") }),
            list("bind", undefined, "Bind", "space", { positional: true, placeholder: "set <word> | reset", showIf: is("action", "bind") }),
          ],
        },
      ],
    },
  ],
};

export const systemSection: Section = {
  id: "system",
  title: "System & tools",
  icon: "wrench",
  blurb: "Diagnose the install, put the scripts on PATH, configure defaults, read the wiki, look up error codes.",
  groups: [
    {
      title: "Install",
      commands: [
        {
          id: "doctor",
          title: "Doctor",
          summary: "Environment diagnostic; --fix installs missing dependencies.",
          icon: "stethoscope",
          program: "hypernix",
          base: ["doctor"],
          fields: [toggle("fix", "--fix", "Install what is missing")],
        },
        {
          id: "devices",
          title: "Devices",
          summary: "What accelerators this machine has, and what each can do.",
          icon: "cpu",
          program: "hypernix",
          base: ["devices"],
          fields: [toggle("json", "--json", "JSON")],
        },
        {
          id: "path",
          title: "Scripts on PATH",
          summary: "Put hypernix's console scripts on your shell's PATH.",
          icon: "terminal",
          program: "hypernix",
          base: ["path"],
          fields: [
            pick("mode", undefined, "Do", [
              { value: "--check", label: "Check (writes nothing)" },
              { value: "--apply", label: "Apply to shell startup" },
              { value: "--undo", label: "Undo" },
              { value: "--print", label: "Print the snippet" },
            ], { positional: true, default: "--check" }),
            pick("shell", "--shell", "Shell", ["", "bash", "zsh", "fish", "sh"]),
            path("profile", "--profile", "Startup file", "file", { advanced: true }),
            toggle("force", "--force", "Allow inside a virtualenv", { advanced: true }),
          ],
        },
        {
          id: "config",
          title: "Defaults",
          summary: "HyperNix's own configuration: the default model and other keys.",
          icon: "settings",
          program: "hypernix",
          base: ["config"],
          fields: [
            action(["list", "get", "dmodel", "dmodel-experimental", "reset", "path"]),
            text("value", undefined, "Value", {
              positional: true,
              required: true,
              placeholder: "Qwen/Qwen3-14B or a key name",
              showIf: is("action", "get", "dmodel", "dmodel-experimental"),
            }),
            text("resetKey", undefined, "Key (blank for all)", { positional: true, showIf: is("action", "reset") }),
          ],
        },
      ],
    },
    {
      title: "Reference",
      commands: [
        {
          id: "wiki",
          title: "Wiki",
          summary: "Module documentation, read from the installed source.",
          icon: "book",
          program: "hypernix",
          base: ["wiki"],
          fields: [
            text("module", undefined, "Module", { positional: true, placeholder: "pressure_cooker_v5" }),
            text("search", "--search", "Search"),
            toggle("quick", "-q", "Stream section by section"),
            toggle("browser", "-b", "Open in browser"),
          ],
        },
        {
          id: "errors",
          title: "Error codes",
          summary: "What an L#-NNNNN.kS code means and what to do about it.",
          icon: "bug",
          program: "hypernix",
          base: ["errors"],
          fields: [
            action(["explain", "list"]),
            text("code", undefined, "Code", { positional: true, required: true, placeholder: "L2-00412.c3", showIf: is("action", "explain") }),
            text("domain", undefined, "Domain", { positional: true, showIf: is("action", "list") }),
          ],
        },
        {
          id: "elements",
          title: "Elements · addons",
          summary: "Hydrogen, carbon, magnesium and your own addons.",
          icon: "atom",
          program: "hypernix",
          base: ["elements"],
          fields: [
            action(["list", "info", "plan", "run", "new"]),
            text("name", undefined, "Element", { positional: true, required: true, showIf: is("action", "info", "plan", "run", "new") }),
            toggle("experimental", "--experimental", "Periods 6 and 7", { before: true, advanced: true }),
          ],
        },
        {
          id: "net",
          title: "Network & Tailscale",
          summary: "Distributed network manager: Tailscale, peers, ports and shared storage.",
          icon: "network",
          program: "hypernix",
          base: ["net"],
          fields: [
            action([
              { value: "status", label: "status · tailscale status" },
              { value: "m-ip", label: "m-ip · local tailscale IP" },
              { value: "config", label: "config · local net config" },
              { value: "auto-setup", label: "auto-setup · Tailscale & SSH" },
              { value: "m-setup", label: "m-setup · manual instructions" },
              { value: "connect", label: "connect · a peer" },
              { value: "a-il", label: "a-il · connect to every peer" },
              { value: "mutli-a-port", label: "mutli-a-port · add an active port" },
              { value: "ex-port", label: "ex-port · expose a port" },
              { value: "s-storage", label: "s-storage · sync storage" },
              { value: "onef-all", label: "onef-all · central storage node" },
              { value: "tail", label: "tail · distributed execution" },
            ]),
            list("args", undefined, "Arguments", "space", { positional: true, showIf: is("action", "connect", "mutli-a-port", "ex-port", "tail", "config") }),
          ],
        },
        {
          id: "wakeup",
          title: "Wake word",
          summary: "Train a trigger phrase, then listen for it.",
          icon: "radio",
          program: "hypernix",
          base: ["wakeup"],
          tui: true,
          fields: [action(["listen", "record", "train", "check"])],
        },
        {
          id: "cli-menu",
          title: "HyperNix menu",
          summary: "The interactive TUI menu for every HyperNix operation.",
          icon: "command",
          program: "hypernix",
          base: ["cli"],
          tui: true,
          fields: [],
        },
      ],
    },
  ],
};
