import type { Section } from "./types";
import { DTYPES, action, area, is, list, num, path, pick, text, toggle } from "./shared";

const BREW_PRESETS = ["cpu-nano", "cpu-tiny", "cpu-small", "33m", "micro", "small", "medium", "large"];
const fuseCommon = [
  num("target", "--target", "Target °C", { placeholder: "80", showIf: is("action", "status", "plan", "watch") }),
  num("trip", "--trip", "Trip °C", { placeholder: "90", showIf: is("action", "status", "plan", "watch") }),
  num("reset", "--reset", "Resume below °C", { placeholder: "78", showIf: is("action", "status", "plan", "watch") }),
  num("cpuTrip", "--cpu-trip", "CPU trip °C", { advanced: true, showIf: is("action", "status", "plan", "watch") }),
  num("interval", "--interval", "Sensor interval s", { advanced: true, placeholder: "2", showIf: is("action", "status", "plan", "watch") }),
  num("maxEase", "--max-ease", "Max pause fraction", { advanced: true, placeholder: "0.5", step: 0.05, showIf: is("action", "status", "plan", "watch") }),
];

export const trainingSection: Section = {
  id: "training",
  title: "Training",
  icon: "flask",
  blurb: "Initialise, expand and train HyperNix models; brew custom architectures; fuse models; keep the GPU cool.",
  groups: [
    {
      title: "HyperNix models",
      commands: [
        {
          id: "train-run",
          title: "Train",
          summary: "A causal-LM training loop with Abbicus curricula, STML context folding and memory savers.",
          icon: "flame",
          program: "hypernix",
          base: ["train", "run"],
          doc: "wiki/Training.md",
          keywords: "train run abbicus stml fine-tune",
          fields: [
            path("modelDir", "--model-dir", "Model snapshot", "dir", { required: true }),
            path("dataset", "--dataset", "Dataset (raw text)", "file", { required: true }),
            path("outDir", "--out-dir", "Output folder", "dir", { required: true }),
            num("steps", "--steps", "Steps", { placeholder: "1000" }),
            num("batch", "--batch-size", "Batch size", { placeholder: "2" }),
            num("ctx", "--context-length", "Context length", { placeholder: "512" }),
            num("lr", "--lr", "Learning rate", { placeholder: "3e-4", step: 0.0001 }),
            pick("dtype", "--dtype", "Precision", ["", ...DTYPES]),
            text("device", "--device", "Device", { placeholder: "auto", advanced: false }),
            pick("curriculum", undefined, "Curriculum", [
              { value: "", label: "None" },
              { value: "--use-abbicus", label: "Abbicus · linear" },
              { value: "--use-turbo-abbicus", label: "TurboAbbicus · exponential" },
            ], { positional: true }),
            toggle("stml", "--use-stml", "STML: fold long sequences", { help: "Short Term Memory Loss context manager." }),
            num("untrainedMax", "--untrained-max-context", "Untrained max context", { placeholder: "8192", showIf: (v) => v.stml === true }),
            num("segment", "--segment-length", "Segment length", { placeholder: "512", showIf: (v) => v.stml === true }),
            toggle("gc", "--gradient-checkpointing", "Gradient checkpointing", { advanced: true, help: "~30% more compute for most of the activation memory." }),
            num("ckEvery", "--checkpoint-every", "Checkpoint every Nth block", { advanced: true, showIf: (v) => v.gc === true }),
            toggle("fuse", "--fuse-optimizer", "Fused optimizer step", { advanced: true, help: "Needs grad clip 0." }),
            toggle("tune", "--tune-allocator", "Tune CUDA allocator", { advanced: true }),
            num("thermal", "--thermal-target", "Thermal target °C", { advanced: true, help: "Pause between steps to stay below this." }),
            num("wd", "--weight-decay", "Weight decay", { advanced: true, placeholder: "0.1" }),
            num("clip", "--grad-clip", "Grad clip", { advanced: true, placeholder: "1.0" }),
            num("logEvery", "--log-every", "Log every", { advanced: true, placeholder: "10" }),
            num("saveEvery", "--save-every", "Save every", { advanced: true, placeholder: "500" }),
            num("seed", "--seed", "Seed", { advanced: true }),
          ],
        },
        {
          id: "train-init",
          title: "Initialise",
          summary: "Create a fresh HyperNix snapshot of any shape.",
          icon: "sparkles",
          program: "hypernix",
          base: ["train", "init"],
          fields: [
            path("outDir", "--out-dir", "Output folder", "dir", { required: true }),
            text("tokenizer", "--tokenizer-source", "Tokenizer from", { placeholder: "HF repo or folder" }),
            num("vocab", "--vocab-size", "Vocab size", { placeholder: "32000" }),
            num("hidden", "--hidden-size", "Hidden size", { placeholder: "1024" }),
            num("inter", "--intermediate-size", "FFN size", { placeholder: "4096" }),
            num("layers", "--num-hidden-layers", "Layers", { placeholder: "16" }),
            num("heads", "--num-attention-heads", "Heads", { placeholder: "16" }),
            num("kvHeads", "--num-key-value-heads", "KV heads", { advanced: true }),
            num("maxPos", "--max-position-embeddings", "Max positions", { placeholder: "2048", advanced: true }),
            num("rope", "--rope-theta", "RoPE theta", { placeholder: "10000", advanced: true }),
            toggle("tie", "--tie-word-embeddings", "Tie embeddings", { advanced: true }),
            num("seed", "--seed", "Seed", { advanced: true }),
          ],
        },
        {
          id: "train-expand",
          title: "Expand",
          summary: "Warm-start a bigger model from a smaller one.",
          icon: "maximize",
          program: "hypernix",
          base: ["train", "expand"],
          fields: [
            path("src", "--src-dir", "From", "dir", { required: true }),
            path("dst", "--dst-dir", "To", "dir", { required: true }),
            num("hidden", "--hidden-size", "Hidden size"),
            num("inter", "--intermediate-size", "FFN size"),
            num("layers", "--num-hidden-layers", "Layers"),
            num("heads", "--num-attention-heads", "Heads"),
            num("vocab", "--vocab-size", "Vocab size", { advanced: true }),
            num("std", "--init-std", "Init std", { placeholder: "0.02", step: 0.001, advanced: true }),
            num("seed", "--seed", "Seed", { advanced: true }),
          ],
        },
        {
          id: "scriptgen",
          title: "Script builder",
          summary: "Generate a HyperNix training script, or inject a config block into one.",
          icon: "fileCog",
          program: "hnx-scriptgen",
          base: [],
          keywords: "scriptgen preset",
          fields: [
            toggle("cli", "--cli", "Headless (no scriptgen window)", { default: true }),
            path("output", "-o", "Write to", "save", { extensions: ["py", "json", "env"] }),
            path("inject", "--inject", "Inject into script", "file", { extensions: ["py"] }),
            path("preset", "--preset", "Preset", "file", { extensions: ["json"] }),
            list("set", "--set", "Parameters", "repeat", { placeholder: "learning_rate=3e-5", wide: true }),
            pick("format", "--format", "Format", ["", "python", "json", "env"], { advanced: true }),
            toggle("configOnly", "--config-only", "Config only", { advanced: true }),
            toggle("listParams", "--list-params", "List every parameter", { advanced: true }),
          ],
        },
      ],
    },
    {
      title: "Brewer & fusion",
      commands: [
        {
          id: "brew",
          title: "Brewer",
          summary: "Build and train custom models from presets, then export to GGUF.",
          icon: "cooker",
          program: "hypernix",
          base: ["brew"],
          keywords: "brew custom architecture",
          fields: [
            action(["new", "list", "train", "export", "gguf"]),
            pick("preset", "--preset", "Preset", BREW_PRESETS, { required: true, default: "cpu-tiny", showIf: is("action", "new") }),
            text("name", "--name", "Model name", { showIf: is("action", "new", "train", "export") }),
            path("saveDir", "--save-dir", "Save under", "dir", { showIf: is("action", "new"), advanced: true }),
            path("dir", "--dir", "Model folder", "dir", { showIf: is("action", "train", "export"), help: "Instead of a name." }),
            path("data", "--data", "Training text", "file", { required: true, showIf: is("action", "train") }),
            num("steps", "--steps", "Steps", { showIf: is("action", "train") }),
            num("lr", "--lr", "Learning rate", { showIf: is("action", "train"), step: 0.0001 }),
            num("batch", "--batch-size", "Batch size", { showIf: is("action", "train") }),
            pick("device", "--device", "Device", ["", "auto", "cpu", "cuda", "mps"], { showIf: is("action", "train") }),
            path("source", undefined, "Folder or .pt", "dir", { positional: true, required: true, showIf: is("action", "gguf") }),
            pick("format", "--format", "Format", ["", "gguf", "pt", "hnxg"], { showIf: is("action", "export") }),
            path("out", "--out", "Output", "save", { showIf: is("action", "export") }),
            path("o", "-o", "Output", "save", { showIf: is("action", "gguf") }),
            pick("outtype", "--outtype", "Out type", ["", "f32", "f16", "bf16", "q8_0"], { showIf: is("action", "export", "gguf") }),
            text("tokenizer", "--tokenizer", "Tokenizer", { showIf: is("action", "export", "gguf"), advanced: true }),
            text("context", "--context", "Context", { placeholder: "auto | full | N", showIf: is("action", "export", "gguf"), advanced: true }),
            num("padFfn", "--pad-ffn", "Pad FFN to multiple of", { showIf: is("action", "gguf"), advanced: true }),
          ],
        },
        {
          id: "fizzle",
          title: "Fizzle · fuse models",
          summary: "Fuse models and LoRAs into one architecture.",
          icon: "combine",
          program: "hypernix",
          base: ["fiz"],
          keywords: "fuse lora merge fizzle",
          fields: [
            text("m1", "model1", "Model 1", { required: true, placeholder: "Qwen/Qwen1.5-0.5B", help: "Hugging Face id or link." }),
            text("m2", "model2", "Model 2", { placeholder: "openai/whisper-tiny" }),
            text("m3", "model3", "Model 3", { advanced: true }),
            text("lora", "loRA1", "LoRA", { placeholder: "./my_qwen_lora" }),
            text("lora2", "loRA2", "LoRA 2", { advanced: true }),
            path("out", "--out", "Output folder", "dir"),
          ],
        },
        {
          id: "camo",
          title: "Camouflage · RLHF/RLAF",
          summary: "Align a local model, optionally with an AI evaluator.",
          icon: "scale",
          program: "hypernix",
          base: ["camo"],
          fields: [
            text("local", "-Lmodel", "Model to align", { required: true, placeholder: "folder, HF id or link" }),
            num("steps", "-s", "Steps"),
            toggle("ai", "-Ai", "AI-assisted evaluation (RLAF)"),
            text("evalModel", "-M", "Evaluator model", { showIf: (v) => v.ai === true }),
            area("sys", "-Sp", "Evaluator system prompt", { showIf: (v) => v.ai === true }),
          ],
        },
        {
          id: "neuron",
          title: "Neuron · acting networks",
          summary: "Imitation, DAgger and RL for small policies.",
          icon: "brain",
          program: "hypernix",
          base: ["neuron"],
          fields: [
            action(["demo", "clone", "dagger", "rl", "eval"]),
            pick("env", "--env", "Environment", ["grid", "beam"], { default: "grid" }),
            path("out", "-o", "Output", "save", { showIf: is("action", "demo", "clone", "dagger", "rl") }),
            num("episodes", "--episodes", "Episodes", { showIf: is("action", "demo") }),
            path("demos", "--demos", "Demonstrations", "file", { showIf: is("action", "clone") }),
            num("rounds", "--rounds", "Rounds", { showIf: is("action", "dagger") }),
            text("algorithm", "--algorithm", "Algorithm", { placeholder: "reinforce", showIf: is("action", "rl") }),
            path("policy", "--policy", "Policy", "file", { showIf: is("action", "eval") }),
          ],
        },
        {
          id: "dilute",
          title: "Dilute · best-of-n",
          summary: "Generate several answers per prompt and keep the best, for training data.",
          icon: "filter",
          program: "hypernix",
          base: ["dilute"],
          fields: [
            action(["run", "jit", "inspect"]),
            path("prompts", "--prompts", "Prompts file", "file", { showIf: is("action", "run", "jit") }),
            path("out", "-o", "Traces out", "save", { showIf: is("action", "run", "jit") }),
            num("traces", "--traces", "Traces", { showIf: is("action", "run", "jit") }),
            text("judge", "--judge-model", "Judge model", { showIf: is("action", "run", "jit") }),
            path("file", undefined, "Trace file", "file", { positional: true, showIf: is("action", "inspect") }),
          ],
        },
      ],
    },
    {
      title: "Data & hardware",
      commands: [
        {
          id: "gather",
          title: "Gather · crawl a corpus",
          summary: "Crawl a site into a training corpus, robots-aware. Nothing downloaded is executed.",
          icon: "globe",
          program: "hypernix",
          base: ["gather"],
          keywords: "crawl scrape dataset corpus",
          fields: [
            action(["crawl", "probe", "formats"]),
            text("site", "-W", "Site", { placeholder: "https://example.com", showIf: is("action", "crawl", "probe") }),
            text("listSites", "-L", "Several sites", { placeholder: "a.com,b.com", showIf: is("action", "crawl", "probe"), advanced: true }),
            pick("format", "-f", "Format", ["", "jsonl", "text", "html", "html-full", "html-full-wimages", "parquet", "sqlite", "js"], { showIf: is("action", "crawl") }),
            num("depth", "-Q", "Link depth", { placeholder: "1", showIf: is("action", "crawl") }),
            num("threads", "-T", "Threads", { showIf: is("action", "crawl") }),
            num("pause", "-p", "Pause per host s", { placeholder: "1.0", step: 0.1, showIf: is("action", "crawl", "probe") }),
            path("output", "-o", "Output", "dir", { showIf: is("action", "crawl") }),
            num("maxPages", "--max-pages", "Max pages", { showIf: is("action", "crawl"), advanced: true }),
            num("maxSeconds", "--max-seconds", "Max seconds", { showIf: is("action", "crawl"), advanced: true }),
            text("include", "--include", "Only URLs matching", { showIf: is("action", "crawl"), advanced: true }),
            text("exclude", "--exclude", "Never URLs matching", { showIf: is("action", "crawl"), advanced: true }),
            toggle("anyHost", "--any-host", "Follow off-site links", { showIf: is("action", "crawl"), advanced: true }),
            toggle("noRobots", "--no-robots", "Ignore robots.txt", { showIf: is("action", "crawl"), advanced: true }),
            pick("compress", undefined, "Compress", ["", "--xz", "--gz", "--zip", "--7z"], { positional: true, showIf: is("action", "crawl"), advanced: true }),
            text("upload", "-U", "Upload to repo", { showIf: is("action", "crawl"), advanced: true }),
            num("requests", "-u", "Probe requests", { showIf: is("action", "probe") }),
            toggle("json", "--json", "JSON output", { advanced: true, showIf: is("action", "crawl", "probe") }),
          ],
        },
        {
          id: "scavenger",
          title: "Scavenger · find datasets",
          summary: "Discover Hugging Face datasets for training, by size, age and likes.",
          icon: "telescope",
          program: "hypernix",
          base: ["scavenger"],
          fields: [
            text("keywords", "--keywords", "Keywords", { placeholder: "code,math", wide: true }),
            num("maxStorage", "--max-storage", "Max GB each"),
            num("maxTotal", "--max-total", "Max GB total"),
            num("minLikes", "--min-likes", "Min likes", { advanced: true }),
            num("minEntries", "--min-entries", "Min entries", { advanced: true }),
            num("maxAge", "--max-age", "Max age (days)", { advanced: true }),
            pick("dataType", "--data-type", "Data type", ["", "jsonl", "parquet", "csv"], { advanced: true }),
            num("limit", "--limit", "Limit per query", { advanced: true }),
            text("download", "--download", "Download dataset id"),
          ],
        },
        {
          id: "stml",
          title: "STML calculator",
          summary: "How much context a model can train with in the VRAM you have.",
          icon: "memory",
          program: "hypernix",
          base: ["stml"],
          keywords: "vram context calculator",
          fields: [
            num("vram", "--vram", "VRAM (GB)", { required: true, default: "8", step: 0.5 }),
            num("params", "--params", "Parameters (B)", { step: 0.1, placeholder: "1.0" }),
            num("batch", "--batch-size", "Batch size"),
            pick("precision", "--precision", "Precision", ["", "fp32", "fp16", "int8", "int4"]),
            num("layers", "--num-layers", "Layers", { advanced: true }),
            num("heads", "--num-heads", "Heads", { advanced: true }),
            num("headDim", "--head-dim", "Head dim", { advanced: true }),
          ],
        },
        {
          id: "fusebox",
          title: "Fusebox · thermal governor",
          summary: "Hold a GPU at a temperature you choose and stop a run that goes past a limit.",
          icon: "thermometer",
          program: "hypernix",
          base: ["fusebox"],
          keywords: "gpu temperature underclock thermal",
          fields: [
            action(["status", "plan", "watch", "restore"]),
            ...fuseCommon,
            toggle("underclock", "--underclock", "Allow underclocking", { showIf: is("action", "watch") }),
            toggle("yes", "--yes", "Confirm hardware changes", { showIf: is("action", "watch", "restore") }),
            toggle("cpuThreads", "--cpu-threads", "Halve torch threads while easing", { showIf: is("action", "watch"), advanced: true }),
            num("count", "-n", "Stop after reads", { showIf: is("action", "watch"), advanced: true }),
            toggle("json", "--json", "JSON output", { advanced: true }),
          ],
        },
      ],
    },
  ],
};

