import type { CommandSpec, Field, Section } from "./types";
import { WAITER_OVERRIDES, action, area, is, list, num, path, pick, secret, text, toggle } from "./shared";

const w = (
  id: string,
  title: string,
  summary: string,
  icon: CommandSpec["icon"],
  fields: Field[] = [],
  extra: Partial<CommandSpec> = {},
): CommandSpec => ({
  id: `waiter-${id}`,
  title,
  summary,
  icon,
  program: "waiter",
  base: [id],
  fields: [...fields, ...WAITER_OVERRIDES],
  ...extra,
});

export const waiterSection: Section = {
  id: "waiter",
  title: "Waiter · T1 client",
  icon: "radio",
  blurb: "Connect this machine to any T1 server: set up, check, route, and administer it. Needs no server extra.",
  groups: [
    {
      title: "Connect",
      commands: [
        {
          id: "waiter-serv",
          title: "Set up connection",
          summary: "waiter serv: validate a key, save the server, seal the key as v2.1, refresh, update, conceal.",
          icon: "cable",
          program: "waiter",
          base: ["serv"],
          doc: "wiki/Waiter-TUI.md",
          keywords: "serv setup connect -A -E -K -I",
          fields: [
            text("server", "-I", "Server", { required: true, placeholder: "https://myserver.ts.net or 100.x.y.z" }),
            secret("key", "-K", "Key", { placeholder: "T1_… / T2_… / T2C_…" }),
            num("port", "-P", "Port", { placeholder: "8000" }),
            toggle("auto", "-A", "Set up: check the key and save", { default: true }),
            toggle("encrypt", "-E", "Seal as a v2.1 key, encrypt config"),
            toggle("refresh", "-R", "Refresh models"),
            toggle("sync", "-y", "Sync settings from the server"),
            toggle("security", "-S", "Security check"),
            toggle("info", "-Y", "Show the server's public card"),
            toggle("local", "-L", "Local/Tailscale only", { advanced: true }),
            toggle("forceRefresh", "-Rf", "Full refresh", { advanced: true }),
            toggle("update", "-u", "Update hypernix to the server's version", { advanced: true }),
            toggle("updateExact", "--update-exact", "…exactly that version", { advanced: true }),
            toggle("dryRun", "--dry-run", "Print the pip command only", { advanced: true }),
            toggle("conceal", "-c", "Conceal this key (level 3+)", { advanced: true }),
            toggle("noConceal", "--no-conceal", "Stop concealing", { advanced: true }),
            toggle("lock", "-e", "Lock config with a password", { advanced: true }),
            toggle("unlock", "--unlock", "Remove the password lock", { advanced: true }),
            toggle("promote", "--promote-admin", "Request admin promotion", { advanced: true }),
            path("kit", "-k", "Install kit", "file", { advanced: true, extensions: ["zip"] }),
            list("blacklist", "-B", "Block IP/CIDR", "repeat", { advanced: true }),
            list("whitelist", "-W", "Allow IP/CIDR", "repeat", { advanced: true }),
            list("appeal", "-a", "Remove IP/CIDR", "repeat", { advanced: true }),
            list("limit", "-r", "Force limit", "repeat", { advanced: true, placeholder: "key:abc123=60/60s" }),
            list("config", "-C", "Extra config", "repeat", { advanced: true, placeholder: "KEY=VALUE" }),
            text("home", "-H", "Home URL", { advanced: true }),
            path("configFile", "-F", "Config file", "file", { advanced: true }),
            toggle("save", "-s", "Save to .jsonl", { advanced: true }),
            toggle("json", "--json", "Raw JSON", { advanced: true }),
          ],
        },
        w("status", "Server status", "Version, backend, model count and protections.", "activity"),
        w("health", "Health", "Liveness check.", "stethoscope"),
        w("whoami", "Who am I", "Validate the configured key and show its scopes.", "fingerprint"),
        w("doctor", "Production doctor", "Check a server's configuration for production readiness.", "shield"),
        w("smoke", "Smoke tests", "Run smoke tests against a server.", "checklist", [
          toggle("write", "--write", "Also write tests (scratch module)"),
          toggle("failFast", "--fail-fast", "Stop at first failure"),
        ]),
        w("tui", "Dashboard", "The full curses dashboard.", "dashboard", [], { tui: true }),
        w("config", "Saved config", "The locally saved waiter config.", "fileText"),
        {
          id: "waiter-version",
          title: "Versions",
          summary: "Package, T1 API and key-format versions.",
          icon: "info",
          program: "waiter",
          base: ["version"],
          fields: [toggle("json", "--json", "JSON")],
        },
      ],
    },
    {
      title: "Models & routing",
      commands: [
        w("models", "Models", "Models in the server's registry.", "boxes"),
        w("model", "Model detail", "Availability and usage for one model.", "search", [
          text("modelId", undefined, "Model id", { positional: true, required: true }),
        ]),
        w("route", "Route", "Ask the routing engine which model to use.", "shuffle", [
          text("plan", "--plan", "Plan", { required: true, placeholder: "free" }),
          text("model", "--model", "Model"),
          num("inputTokens", "--input-tokens", "Input tokens"),
          toggle("fallback", "--auto-fallback", "Fall through the cascade"),
        ]),
        w("usage", "Usage", "Current usage, or the remaining allowance for a model.", "gauge", [
          text("model", "--model", "Model id"),
        ]),
        w("lmstudio", "LM Studio bridge", "Status, models and chat through a model loaded in LM Studio.", "plug", [
          action(["status", "models", "chat", "local"]),
          toggle("discover", "--discover", "Sweep localhost and the tailnet", { showIf: is("action", "status") }),
          area("prompt", undefined, "Prompt", { positional: true, required: true, showIf: is("action", "chat") }),
        ]),
      ],
    },
    {
      title: "HyperLink & jobs",
      commands: [
        w("hyperlink", "HyperLink", "Pair phones, manage devices and server-side chat sessions.", "phone", [
          action(["devices", "pair", "unpair", "endpoints", "sessions", "chat"]),
          text("label", "--label", "Device label", { showIf: is("action", "pair") }),
          toggle("qr", "--qr", "Print the QR payload", { showIf: is("action", "pair") }),
          toggle("all", "--all", "Include revoked", { showIf: is("action", "devices") }),
          text("device", undefined, "Device id", { positional: true, required: true, showIf: is("action", "unpair") }),
          text("session", undefined, "Session id", { positional: true, required: true, showIf: is("action", "chat") }),
          area("message", undefined, "Message", { positional: true, required: true, showIf: is("action", "chat") }),
        ]),
        w("jobs", "Jobs", "Get or cancel a server job.", "timer", [
          action(["get", "cancel"]),
          text("jobId", undefined, "Job id", { positional: true, required: true }),
        ]),
        w("events", "Events", "Poll recent server events.", "scroll", [
          num("limit", "--limit", "Limit"),
          text("since", "--since", "After event id"),
        ]),
        w("modules", "Modules", "List modules, or create / upload / sync one.", "package", [
          text("create", "--create", "Create named"),
          text("version", "--version", "Version", { placeholder: "1.0.0", showIf: (v) => !!v.create }),
          text("upload", "--upload", "Upload to module id"),
          path("file", "--file", "File", "file", { showIf: (v) => !!v.upload }),
          text("syncId", "--sync", "Sync module id", { advanced: true }),
          text("serverId", "--server-id", "To server id", { advanced: true }),
        ]),
        w("deploy", "Deploy", "Push a module to trusted servers.", "rocket", [
          text("moduleId", undefined, "Module id", { positional: true, required: true }),
          text("to", "--to", "Server ids", { required: true, placeholder: "srv1,srv2" }),
          toggle("wait", "--wait", "Wait until settled"),
          num("timeout", "--timeout", "Timeout s", { advanced: true }),
        ]),
        w("servers", "Servers", "List or register servers.", "server", [
          text("register", "--register", "Register name"),
          text("address", "--address", "Address", { showIf: (v) => !!v.register }),
          toggle("private", "--allow-private", "Allow private address", { showIf: (v) => !!v.register }),
        ]),
        {
          id: "waiter-kits",
          title: "Kits",
          summary: "Installed kits: list, remove, or run one. Install with waiter serv -k.",
          icon: "package",
          program: "waiter",
          base: ["kits"],
          fields: [
            action(["list", "remove", "run"]),
            text("name", undefined, "Kit", { positional: true, required: true, showIf: is("action", "remove", "run") }),
            list("cmd", undefined, "Command", "space", { positional: true, required: true, showIf: is("action", "run") }),
          ],
        },
        {
          id: "waiter-find",
          title: "Find a server",
          summary: "Find a T1 server by name, Host ID or api.jsonl.",
          icon: "search",
          program: "waiter",
          base: ["-F"],
          fields: [
            text("query", undefined, "Name / Host ID / api.jsonl", { positional: true, required: true }),
            toggle("local", "-l", "Local only"),
          ],
        },
      ],
    },
    {
      title: "Admin & billing",
      commands: [
        w("keys", "Keys", "List keys; assign a plan, account or models; import.", "key", [
          text("assign", "--assign", "Assign to key id"),
          text("plan", "--plan", "Plan", { showIf: (v) => !!v.assign }),
          text("account", "--account", "Account id", { showIf: (v) => !!v.assign, advanced: true }),
          text("user", "--user", "User id", { showIf: (v) => !!v.assign, advanced: true }),
          text("models", "--models", "Models", { showIf: (v) => !!v.assign, placeholder: "a,b" }),
          text("servers", "--servers", "Servers", { showIf: (v) => !!v.assign, advanced: true }),
          path("importFile", "--import-file", "Import file", "file", { advanced: true }),
          toggle("inactive", "--include-inactive", "Include inactive"),
        ]),
        w("security", "Network policy", "Block, allow or appeal addresses; forced limits.", "shield", [
          text("block", "--block", "Block CIDR"),
          text("allow", "--allow", "Allow CIDR"),
          text("appeal", "--appeal", "Remove CIDR"),
          text("reason", "--reason", "Reason"),
          pick("unlisted", "--allow-unlisted", "Allow unlisted", ["", "on", "off"], { advanced: true }),
          toggle("limits", "--limits", "Show forced limits"),
          toggle("mine", "--my-rate-limits", "My rate limits"),
        ]),
        w("audit", "Audit trail", "Read the server's audit trail (admin).", "scroll", [
          pick("category", "--category", "Category", ["", "admin", "security", "write", "billing"]),
          pick("outcome", "--outcome", "Outcome", ["", "success", "denied", "failure"]),
          text("action", "--action", "Action", { placeholder: "keys.assign" }),
          num("limit", "--limit", "Limit"),
        ]),
        w("cost", "Cost", "Spend, breakdowns, forecasts and estimates.", "chart", [
          pick("groupBy", "--group-by", "Group by", ["", "model_id", "key_id", "server_id", "module_id", "user_id", "account_id", "endpoint"]),
          pick("range", "--range", "Range", ["", "1h", "24h", "7d", "30d", "all"]),
          toggle("forecast", "--forecast", "Forecast"),
          text("estimate", "--estimate-model", "Estimate for model", { advanced: true }),
          num("in", "--input-tokens", "Input tokens", { advanced: true }),
          num("out", "--output-tokens", "Output tokens", { advanced: true }),
        ]),
        w("billing", "Billing", "Balance and transactions, or redeem a token.", "ticket", [
          toggle("transactions", "--transactions", "Transactions"),
          secret("redeem", "--redeem", "Redeem token"),
        ]),
      ],
    },
  ],
};
